#!/usr/bin/env bash

count=`ps -xc -o command | egrep -c "^Flowdock"`
if [ $count -gt 0 ]; then
  if [[ `osascript /usr/local/bin/activeWindow.scpt` != *Flowdock* ]]
    then
      killall Flowdock
      sleep 1
      open -g /Applications/Flowdock.app
  fi
fi

